// Auto-generated from antar_app_100_deities_full_content.xlsx — do not hand-edit.
// 100 deities, organised into regional / pan-India categories.

export type Deity = {
  no: number;
  /** Region or pan-India family this deity belongs to (e.g., 'South India'). */
  region: string;
  name: string;
  tag: string;
  desc: string;
  /** Sprite portrait crop. Present only for the deities in deities.png. */
  portraitTop?: number;
};

export const DEITY_PORTRAIT_CROP = {
  w: 4.4857,
  h: 15.6646,
  left: -0.3238,
};

/** Distinct region buckets in display order. */
export const DEITY_REGIONS = [
  'North India',
  'South India',
  'East India',
  'West India',
  'Central India',
  'Himalayan / Uttarakhand / HP',
  'Pan-India Ganesha Forms',
  'Pan-India Shakti Forms',
  'Pan-India Vishnu Forms',
  'Pan-India Shiva Forms',
] as const;

export const DEITIES: Deity[] = [
  { no: 1, region: 'North India', name: 'Lord Shiva', tag: 'Mahadev', desc: 'Supreme yogi, destroyer of ego and source of inner stillness', portraitTop: -4.4283 },
  { no: 2, region: 'North India', name: 'Maa Parvati', tag: 'Shakti Swaroopa', desc: 'Mother of strength, devotion and divine feminine grace' },
  { no: 3, region: 'North India', name: 'Lord Vishnu', tag: 'Narayana', desc: 'Preserver of the universe and protector of cosmic balance', portraitTop: -6.6118 },
  { no: 4, region: 'North India', name: 'Maa Lakshmi', tag: 'Shri Mahalakshmi', desc: 'Goddess of prosperity, beauty, abundance and auspiciousness', portraitTop: -5.5038 },
  { no: 5, region: 'North India', name: 'Lord Krishna', tag: 'Govinda', desc: 'Divine guide of love, wisdom, joy and compassion', portraitTop: -7.6993 },
  { no: 6, region: 'North India', name: 'Radha Krishna', tag: 'Divine Love', desc: 'Eternal union of devotion, surrender and spiritual love' },
  { no: 7, region: 'North India', name: 'Lord Rama', tag: 'Maryada Purushottam', desc: 'Embodiment of dharma, truth, courage and righteous living' },
  { no: 8, region: 'North India', name: 'Maa Sita', tag: 'Janaki Mata', desc: 'Symbol of purity, patience, devotion and inner strength' },
  { no: 9, region: 'North India', name: 'Hanuman', tag: 'Sankat Mochan', desc: 'Remover of troubles and giver of devotion, courage and protection' },
  { no: 10, region: 'North India', name: 'Maa Durga', tag: 'Mahishasura Mardini', desc: 'Divine mother who protects, empowers and destroys negativity' },
  { no: 11, region: 'South India', name: 'Lord Venkateswara', tag: 'Srinivasa', desc: 'Bestower of grace, protection, prosperity and divine blessings' },
  { no: 12, region: 'South India', name: 'Lord Murugan', tag: 'Kartikeya', desc: 'Warrior deity of wisdom, courage and spiritual victory' },
  { no: 13, region: 'South India', name: 'Andal', tag: 'Bhakti Devi', desc: 'Saint-goddess of pure devotion and divine love for Vishnu' },
  { no: 14, region: 'South India', name: 'Lord Ayyappa', tag: 'Dharma Shasta', desc: 'Protector of dharma, discipline, devotion and inner strength' },
  { no: 15, region: 'South India', name: 'Meenakshi Amman', tag: 'Divine Queen', desc: 'Goddess of compassion, beauty, wisdom and royal grace' },
  { no: 16, region: 'South India', name: 'Kamakshi Devi', tag: 'Mother of Mercy', desc: 'Divine mother who blesses with love, peace and fulfillment' },
  { no: 17, region: 'South India', name: 'Nataraja', tag: 'Cosmic Dancer', desc: 'Lord Shiva as the dancer of creation, rhythm and transformation' },
  { no: 18, region: 'South India', name: 'Ranganatha Swamy', tag: 'Resting Vishnu', desc: 'Lord Vishnu in cosmic rest, symbol of peace and preservation' },
  { no: 19, region: 'South India', name: 'Padmanabha Swamy', tag: 'Lotus Navel Lord', desc: 'Source of creation, cosmic protection and divine abundance' },
  { no: 20, region: 'South India', name: 'Subramanya Swamy', tag: 'Vel Murugan', desc: 'Divine warrior who removes fear, ignorance and obstacles' },
  { no: 21, region: 'East India', name: 'Lord Jagannath', tag: 'Lord of the Universe', desc: 'Compassionate form of Krishna who welcomes every devotee' },
  { no: 22, region: 'East India', name: 'Balabhadra', tag: 'Divine Strength', desc: 'Elder brother of Jagannath, symbol of power and protection' },
  { no: 23, region: 'East India', name: 'Subhadra Devi', tag: 'Auspicious Sister', desc: 'Goddess of harmony, blessings and sacred family love' },
  { no: 24, region: 'East India', name: 'Maa Kali', tag: 'Adi Shakti', desc: 'Fierce mother who destroys darkness, fear and ego' },
  { no: 25, region: 'East India', name: 'Maa Tara', tag: 'Savior Mother', desc: 'Compassionate goddess who guides through danger and uncertainty' },
  { no: 26, region: 'East India', name: 'Maa Chandi', tag: 'Fierce Protector', desc: 'Warrior goddess who removes evil and protects devotees' },
  { no: 27, region: 'East India', name: 'Gopal Krishna', tag: 'Child Krishna', desc: 'Playful divine child of innocence, joy and loving devotion' },
  { no: 28, region: 'East India', name: 'Maa Manasa', tag: 'Serpent Goddess', desc: 'Goddess of healing, protection and fertility blessings' },
  { no: 29, region: 'East India', name: 'Maa Shitala', tag: 'Healing Mother', desc: 'Goddess of health, cooling grace and protection from disease' },
  { no: 30, region: 'East India', name: 'Maa Kamakhya', tag: 'Yoni Shakti', desc: 'Powerful goddess of creation, fertility and sacred feminine energy' },
  { no: 31, region: 'West India', name: 'Siddhivinayak Ganesha', tag: 'Vighnaharta', desc: 'Remover of obstacles and bestower of wisdom and success' },
  { no: 32, region: 'West India', name: 'Lord Vitthal', tag: 'Panduranga', desc: 'Loving form of Krishna who blesses devotion and humility' },
  { no: 33, region: 'West India', name: 'Rukmini Devi', tag: 'Divine Consort', desc: 'Goddess of devotion, grace, prosperity and loving commitment' },
  { no: 34, region: 'West India', name: 'Khandoba', tag: 'Warrior Protector', desc: 'Fierce guardian deity who protects devotees and destroys evil' },
  { no: 35, region: 'West India', name: 'Tulja Bhavani', tag: 'Warrior Mother', desc: 'Divine mother of power, victory, protection and courage' },
  { no: 36, region: 'West India', name: 'Renuka Devi', tag: 'Mother Goddess', desc: 'Nurturing goddess of protection, family strength and blessings' },
  { no: 37, region: 'West India', name: 'Ranchhodrai Krishna', tag: 'Dwarkadhish', desc: 'Compassionate Krishna who guides devotees with wisdom and love' },
  { no: 38, region: 'West India', name: 'Dattatreya', tag: 'Trinity Guru', desc: 'Unified form of Brahma, Vishnu and Shiva as divine teacher' },
  { no: 39, region: 'West India', name: 'Swaminarayan', tag: 'Supreme Guide', desc: 'Spiritual master of devotion, discipline, purity and service' },
  { no: 40, region: 'West India', name: 'Eklingji Shiva', tag: 'Royal Mahadev', desc: 'Sacred Shiva form worshipped as guardian and divine ruler' },
  { no: 41, region: 'Central India', name: 'Mahakaleshwar', tag: 'Lord of Time', desc: 'Powerful Shiva form who protects from fear, death and negativity' },
  { no: 42, region: 'Central India', name: 'Omkareshwar', tag: 'Omkar Shiva', desc: 'Sacred Shiva form embodying the vibration of Om' },
  { no: 43, region: 'Central India', name: 'Maa Narmada', tag: 'Sacred River Mother', desc: 'Divine river goddess who purifies, nourishes and blesses life' },
  { no: 44, region: 'Central India', name: 'Bhairav Baba', tag: 'Kaal Bhairav', desc: 'Fierce guardian of time, protection and spiritual discipline' },
  { no: 45, region: 'Central India', name: 'Maa Mahamaya', tag: 'Cosmic Mother', desc: 'Goddess of divine illusion, protection and universal power' },
  { no: 46, region: 'Central India', name: 'Chitragupta', tag: 'Divine Recorder', desc: 'Keeper of karma, truth, justice and righteous actions' },
  { no: 47, region: 'Central India', name: 'Maa Vindhyavasini', tag: 'Mountain Goddess', desc: 'Protective mother who grants strength, courage and victory' },
  { no: 48, region: 'Central India', name: 'Ram Raja', tag: 'Divine King', desc: 'Royal form of Rama symbolizing justice, dharma and blessings' },
  { no: 49, region: 'Central India', name: 'Maa Baglamukhi', tag: 'Pitambara Devi', desc: 'Goddess who protects from enemies and stills negative forces' },
  { no: 50, region: 'Central India', name: 'Veer Hanuman', tag: 'Mahabali', desc: 'Powerful protector who grants strength, devotion and fearlessness' },
  { no: 51, region: 'Himalayan / Uttarakhand / HP', name: 'Kedarnath Shiva', tag: 'Himalayan Mahadev', desc: 'Sacred Shiva of the Himalayas, giver of liberation and peace' },
  { no: 52, region: 'Himalayan / Uttarakhand / HP', name: 'Badrinath Vishnu', tag: 'Badri Narayan', desc: 'Vishnu of the holy mountains, protector of dharma and devotion' },
  { no: 53, region: 'Himalayan / Uttarakhand / HP', name: 'Maa Ganga', tag: 'Gangotri Mata', desc: 'Sacred river goddess who purifies sins and blesses the soul' },
  { no: 54, region: 'Himalayan / Uttarakhand / HP', name: 'Maa Yamuna', tag: 'Yamunotri Mata', desc: 'Divine river goddess of devotion, purity and loving grace' },
  { no: 55, region: 'Himalayan / Uttarakhand / HP', name: 'Jwala Devi', tag: 'Eternal Flame', desc: 'Goddess of sacred fire, divine energy and powerful protection' },
  { no: 56, region: 'Himalayan / Uttarakhand / HP', name: 'Naina Devi', tag: 'Divine Eyes', desc: 'Mother goddess who watches, protects and blesses devotees' },
  { no: 57, region: 'Himalayan / Uttarakhand / HP', name: 'Chamunda Devi', tag: 'Fierce Shakti', desc: 'Powerful goddess who destroys evil and grants protection' },
  { no: 58, region: 'Himalayan / Uttarakhand / HP', name: 'Kullu Raghunath', tag: 'Valley Rama', desc: 'Beloved Rama form blessing devotion, culture and community' },
  { no: 59, region: 'Himalayan / Uttarakhand / HP', name: 'Hidimba Devi', tag: 'Forest Mother', desc: 'Protective goddess of strength, nature and ancestral blessings' },
  { no: 60, region: 'Himalayan / Uttarakhand / HP', name: 'Kartikeya', tag: 'Skanda', desc: 'Divine commander who grants courage, wisdom and victory' },
  { no: 61, region: 'Pan-India Ganesha Forms', name: 'Bala Ganesha', tag: 'Child Ganesha', desc: 'Innocent form of Ganesha blessing joy, learning and new beginnings' },
  { no: 62, region: 'Pan-India Ganesha Forms', name: 'Siddhivinayak', tag: 'Success Giver', desc: 'Ganesha who grants success, clarity and obstacle-free progress' },
  { no: 63, region: 'Pan-India Ganesha Forms', name: 'Mahaganapati', tag: 'Great Ganesha', desc: 'Supreme Ganesha form blessing abundance, wisdom and power' },
  { no: 64, region: 'Pan-India Ganesha Forms', name: 'Vakratunda', tag: 'Curved Trunk Lord', desc: 'Ganesha who removes crooked obstacles and negative forces' },
  { no: 65, region: 'Pan-India Ganesha Forms', name: 'Heramba Ganesha', tag: 'Protector Ganesha', desc: 'Five-faced guardian form offering courage and protection' },
  { no: 66, region: 'Pan-India Ganesha Forms', name: 'Ucchishta Ganesha', tag: 'Tantric Ganesha', desc: 'Sacred esoteric form blessing creativity and spiritual mastery' },
  { no: 67, region: 'Pan-India Ganesha Forms', name: 'Lakshmi Ganesha', tag: 'Prosperity Ganesha', desc: 'Ganesha with Lakshmi blessing wealth, success and auspiciousness' },
  { no: 68, region: 'Pan-India Ganesha Forms', name: 'Dancing Ganesha', tag: 'Nritya Ganapati', desc: 'Joyful Ganesha form blessing creativity, rhythm and happiness' },
  { no: 69, region: 'Pan-India Ganesha Forms', name: 'Seated Ganesha', tag: 'Shubh Ganapati', desc: 'Calm Ganesha form blessing peace, wisdom and stability' },
  { no: 70, region: 'Pan-India Ganesha Forms', name: 'Temple Ganesha', tag: 'Blessing Ganapati', desc: 'Sacred temple form blessing devotion and new beginnings' },
  { no: 71, region: 'Pan-India Shakti Forms', name: 'Maa Lakshmi', tag: 'Goddess of Abundance', desc: 'Blesses prosperity, fortune, beauty and auspicious living', portraitTop: -5.5038 },
  { no: 72, region: 'Pan-India Shakti Forms', name: 'Maa Saraswati', tag: 'Veena Vadini', desc: 'Goddess of learning, music, creativity and pure knowledge' },
  { no: 73, region: 'Pan-India Shakti Forms', name: 'Maa Durga', tag: 'Shakti Mata', desc: 'Protective mother who grants courage, victory and divine strength' },
  { no: 74, region: 'Pan-India Shakti Forms', name: 'Maa Kali', tag: 'Mahakali', desc: 'Fierce goddess of transformation, time and liberation' },
  { no: 75, region: 'Pan-India Shakti Forms', name: 'Maa Annapurna', tag: 'Food Giver', desc: 'Goddess who nourishes body, home and soul with abundance' },
  { no: 76, region: 'Pan-India Shakti Forms', name: 'Bhuvaneshwari Devi', tag: 'Queen of Worlds', desc: 'Cosmic mother who holds the universe with compassion' },
  { no: 77, region: 'Pan-India Shakti Forms', name: 'Lalita Tripurasundari', tag: 'Divine Beauty', desc: 'Supreme goddess of beauty, bliss, grace and spiritual power' },
  { no: 78, region: 'Pan-India Shakti Forms', name: 'Rajarajeshwari', tag: 'Royal Mother', desc: 'Majestic goddess of sovereignty, compassion and divine protection' },
  { no: 79, region: 'Pan-India Shakti Forms', name: 'Santoshi Maa', tag: 'Mother of Contentment', desc: 'Goddess who blesses peace, satisfaction and family harmony' },
  { no: 80, region: 'Pan-India Shakti Forms', name: 'Gayatri Maa', tag: 'Veda Mata', desc: 'Mother of wisdom, mantra, light and spiritual awakening' },
  { no: 81, region: 'Pan-India Vishnu Forms', name: 'Narayana', tag: 'Cosmic Vishnu', desc: 'Supreme preserver who sustains creation and protects dharma' },
  { no: 82, region: 'Pan-India Vishnu Forms', name: 'Vamana', tag: 'Dwarf Avatar', desc: 'Vishnu’s humble avatar who restores cosmic balance' },
  { no: 83, region: 'Pan-India Vishnu Forms', name: 'Narasimha', tag: 'Fierce Protector', desc: 'Lion-man avatar who protects devotees and destroys evil' },
  { no: 84, region: 'Pan-India Vishnu Forms', name: 'Kurma', tag: 'Tortoise Avatar', desc: 'Vishnu avatar symbolizing stability, support and patience' },
  { no: 85, region: 'Pan-India Vishnu Forms', name: 'Varaha', tag: 'Boar Avatar', desc: 'Vishnu avatar who rescues Earth and restores order' },
  { no: 86, region: 'Pan-India Vishnu Forms', name: 'Matsya', tag: 'Fish Avatar', desc: 'Vishnu avatar who saves wisdom and protects creation' },
  { no: 87, region: 'Pan-India Vishnu Forms', name: 'Parashurama', tag: 'Warrior Sage', desc: 'Avatar of discipline, justice, courage and divine power' },
  { no: 88, region: 'Pan-India Vishnu Forms', name: 'Krishna', tag: 'Leela Purushottam', desc: 'Divine teacher of love, wisdom, playfulness and devotion' },
  { no: 89, region: 'Pan-India Vishnu Forms', name: 'Rama', tag: 'Dharma Avatar', desc: 'Avatar of truth, duty, compassion and righteous action' },
  { no: 90, region: 'Pan-India Vishnu Forms', name: 'Mohini', tag: 'Enchanting Vishnu', desc: 'Divine feminine form of Vishnu representing beauty and wisdom' },
  { no: 91, region: 'Pan-India Shiva Forms', name: 'Mahadev', tag: 'Supreme Shiva', desc: 'Lord of meditation, transformation, detachment and liberation' },
  { no: 92, region: 'Pan-India Shiva Forms', name: 'Ardhanarishvara', tag: 'Shiva-Shakti Union', desc: 'Divine balance of masculine and feminine cosmic energies' },
  { no: 93, region: 'Pan-India Shiva Forms', name: 'Dakshinamurthy', tag: 'Adi Guru', desc: 'Shiva as the silent teacher of wisdom and self-realization' },
  { no: 94, region: 'Pan-India Shiva Forms', name: 'Bhairava', tag: 'Fierce Shiva', desc: 'Guardian form of Shiva protecting time, temples and devotees' },
  { no: 95, region: 'Pan-India Shiva Forms', name: 'Pashupatinath', tag: 'Lord of Beings', desc: 'Shiva as protector of all living beings and souls' },
  { no: 96, region: 'Pan-India Shiva Forms', name: 'Lingodbhava', tag: 'Infinite Shiva', desc: 'Form of Shiva revealing his boundless cosmic nature' },
  { no: 97, region: 'Pan-India Shiva Forms', name: 'Somnath Shiva', tag: 'Moon-Crowned Lord', desc: 'Sacred Shiva form blessing healing, faith and resilience' },
  { no: 98, region: 'Pan-India Shiva Forms', name: 'Kailash Shiva', tag: 'Himalayan Yogi', desc: 'Meditative Shiva of Mount Kailash, source of silence and peace' },
  { no: 99, region: 'Pan-India Shiva Forms', name: 'Meditation Shiva', tag: 'Yogeshwar', desc: 'Shiva in deep meditation, guiding inner stillness and awareness' },
  { no: 100, region: 'Pan-India Shiva Forms', name: 'Blessing Shiva', tag: 'Ashutosh', desc: 'Compassionate Shiva who quickly blesses sincere devotion' },
];
