// Auto-generated from antar_app_100_deities_content.xlsx — do not hand-edit.
// All 100 rows shipped (placeholder names like 'Deity 11' remain — fill the
// spreadsheet's Deity Name / Epithet / Short Description columns and regenerate.

export type Deity = {
  no: number;
  name: string;
  tag: string;
  desc: string;
  /** Sprite portrait crop. Present only for the deities in deities.png. */
  portraitTop?: number;
};

export const DEITY_PORTRAIT_CROP = {
  w: 4.4857,
  h: 15.6646,
  left: -0.3238,
};

export const DEITIES: Deity[] = [
  { no: 1, name: 'Lord Shiva', tag: 'Mahadev', desc: 'Supreme yogi, destroyer of ego and source of inner stillness', portraitTop: -4.4283 },
  { no: 2, name: 'Maa Parvati', tag: 'Shakti Swaroopa', desc: 'Mother of strength, devotion and divine feminine grace' },
  { no: 3, name: 'Lord Vishnu', tag: 'Narayana', desc: 'Preserver of the universe and protector of cosmic balance', portraitTop: -6.6118 },
  { no: 4, name: 'Maa Lakshmi', tag: 'Shri Mahalakshmi', desc: 'Goddess of prosperity, beauty, abundance and auspiciousness', portraitTop: -5.5038 },
  { no: 5, name: 'Lord Krishna', tag: 'Govinda', desc: 'Divine guide of love, wisdom, joy and compassion', portraitTop: -7.6993 },
  { no: 6, name: 'Radha Krishna', tag: 'Divine Love', desc: 'Eternal union of devotion, surrender and spiritual love' },
  { no: 7, name: 'Lord Rama', tag: 'Maryada Purushottam', desc: 'Embodiment of dharma, truth, courage and righteous living' },
  { no: 8, name: 'Maa Sita', tag: 'Janaki Mata', desc: 'Symbol of purity, patience, devotion and inner strength' },
  { no: 9, name: 'Hanuman', tag: 'Sankat Mochan', desc: 'Remover of troubles and giver of devotion, courage and protection' },
  { no: 10, name: 'Maa Durga', tag: 'Mahishasura Mardini', desc: 'Divine mother who protects, empowers and destroys negativity' },
  { no: 11, name: 'Deity 11', tag: 'Epithet 11', desc: 'Devotional description for Deity 11' },
  { no: 12, name: 'Deity 12', tag: 'Epithet 12', desc: 'Devotional description for Deity 12' },
  { no: 13, name: 'Deity 13', tag: 'Epithet 13', desc: 'Devotional description for Deity 13' },
  { no: 14, name: 'Deity 14', tag: 'Epithet 14', desc: 'Devotional description for Deity 14' },
  { no: 15, name: 'Deity 15', tag: 'Epithet 15', desc: 'Devotional description for Deity 15' },
  { no: 16, name: 'Deity 16', tag: 'Epithet 16', desc: 'Devotional description for Deity 16' },
  { no: 17, name: 'Deity 17', tag: 'Epithet 17', desc: 'Devotional description for Deity 17' },
  { no: 18, name: 'Deity 18', tag: 'Epithet 18', desc: 'Devotional description for Deity 18' },
  { no: 19, name: 'Deity 19', tag: 'Epithet 19', desc: 'Devotional description for Deity 19' },
  { no: 20, name: 'Deity 20', tag: 'Epithet 20', desc: 'Devotional description for Deity 20' },
  { no: 21, name: 'Deity 21', tag: 'Epithet 21', desc: 'Devotional description for Deity 21' },
  { no: 22, name: 'Deity 22', tag: 'Epithet 22', desc: 'Devotional description for Deity 22' },
  { no: 23, name: 'Deity 23', tag: 'Epithet 23', desc: 'Devotional description for Deity 23' },
  { no: 24, name: 'Deity 24', tag: 'Epithet 24', desc: 'Devotional description for Deity 24' },
  { no: 25, name: 'Deity 25', tag: 'Epithet 25', desc: 'Devotional description for Deity 25' },
  { no: 26, name: 'Deity 26', tag: 'Epithet 26', desc: 'Devotional description for Deity 26' },
  { no: 27, name: 'Deity 27', tag: 'Epithet 27', desc: 'Devotional description for Deity 27' },
  { no: 28, name: 'Deity 28', tag: 'Epithet 28', desc: 'Devotional description for Deity 28' },
  { no: 29, name: 'Deity 29', tag: 'Epithet 29', desc: 'Devotional description for Deity 29' },
  { no: 30, name: 'Deity 30', tag: 'Epithet 30', desc: 'Devotional description for Deity 30' },
  { no: 31, name: 'Deity 31', tag: 'Epithet 31', desc: 'Devotional description for Deity 31' },
  { no: 32, name: 'Deity 32', tag: 'Epithet 32', desc: 'Devotional description for Deity 32' },
  { no: 33, name: 'Deity 33', tag: 'Epithet 33', desc: 'Devotional description for Deity 33' },
  { no: 34, name: 'Deity 34', tag: 'Epithet 34', desc: 'Devotional description for Deity 34' },
  { no: 35, name: 'Deity 35', tag: 'Epithet 35', desc: 'Devotional description for Deity 35' },
  { no: 36, name: 'Deity 36', tag: 'Epithet 36', desc: 'Devotional description for Deity 36' },
  { no: 37, name: 'Deity 37', tag: 'Epithet 37', desc: 'Devotional description for Deity 37' },
  { no: 38, name: 'Deity 38', tag: 'Epithet 38', desc: 'Devotional description for Deity 38' },
  { no: 39, name: 'Deity 39', tag: 'Epithet 39', desc: 'Devotional description for Deity 39' },
  { no: 40, name: 'Deity 40', tag: 'Epithet 40', desc: 'Devotional description for Deity 40' },
  { no: 41, name: 'Deity 41', tag: 'Epithet 41', desc: 'Devotional description for Deity 41' },
  { no: 42, name: 'Deity 42', tag: 'Epithet 42', desc: 'Devotional description for Deity 42' },
  { no: 43, name: 'Deity 43', tag: 'Epithet 43', desc: 'Devotional description for Deity 43' },
  { no: 44, name: 'Deity 44', tag: 'Epithet 44', desc: 'Devotional description for Deity 44' },
  { no: 45, name: 'Deity 45', tag: 'Epithet 45', desc: 'Devotional description for Deity 45' },
  { no: 46, name: 'Deity 46', tag: 'Epithet 46', desc: 'Devotional description for Deity 46' },
  { no: 47, name: 'Deity 47', tag: 'Epithet 47', desc: 'Devotional description for Deity 47' },
  { no: 48, name: 'Deity 48', tag: 'Epithet 48', desc: 'Devotional description for Deity 48' },
  { no: 49, name: 'Deity 49', tag: 'Epithet 49', desc: 'Devotional description for Deity 49' },
  { no: 50, name: 'Deity 50', tag: 'Epithet 50', desc: 'Devotional description for Deity 50' },
  { no: 51, name: 'Deity 51', tag: 'Epithet 51', desc: 'Devotional description for Deity 51' },
  { no: 52, name: 'Deity 52', tag: 'Epithet 52', desc: 'Devotional description for Deity 52' },
  { no: 53, name: 'Deity 53', tag: 'Epithet 53', desc: 'Devotional description for Deity 53' },
  { no: 54, name: 'Deity 54', tag: 'Epithet 54', desc: 'Devotional description for Deity 54' },
  { no: 55, name: 'Deity 55', tag: 'Epithet 55', desc: 'Devotional description for Deity 55' },
  { no: 56, name: 'Deity 56', tag: 'Epithet 56', desc: 'Devotional description for Deity 56' },
  { no: 57, name: 'Deity 57', tag: 'Epithet 57', desc: 'Devotional description for Deity 57' },
  { no: 58, name: 'Deity 58', tag: 'Epithet 58', desc: 'Devotional description for Deity 58' },
  { no: 59, name: 'Deity 59', tag: 'Epithet 59', desc: 'Devotional description for Deity 59' },
  { no: 60, name: 'Deity 60', tag: 'Epithet 60', desc: 'Devotional description for Deity 60' },
  { no: 61, name: 'Deity 61', tag: 'Epithet 61', desc: 'Devotional description for Deity 61' },
  { no: 62, name: 'Deity 62', tag: 'Epithet 62', desc: 'Devotional description for Deity 62' },
  { no: 63, name: 'Deity 63', tag: 'Epithet 63', desc: 'Devotional description for Deity 63' },
  { no: 64, name: 'Deity 64', tag: 'Epithet 64', desc: 'Devotional description for Deity 64' },
  { no: 65, name: 'Deity 65', tag: 'Epithet 65', desc: 'Devotional description for Deity 65' },
  { no: 66, name: 'Deity 66', tag: 'Epithet 66', desc: 'Devotional description for Deity 66' },
  { no: 67, name: 'Deity 67', tag: 'Epithet 67', desc: 'Devotional description for Deity 67' },
  { no: 68, name: 'Deity 68', tag: 'Epithet 68', desc: 'Devotional description for Deity 68' },
  { no: 69, name: 'Deity 69', tag: 'Epithet 69', desc: 'Devotional description for Deity 69' },
  { no: 70, name: 'Deity 70', tag: 'Epithet 70', desc: 'Devotional description for Deity 70' },
  { no: 71, name: 'Deity 71', tag: 'Epithet 71', desc: 'Devotional description for Deity 71' },
  { no: 72, name: 'Deity 72', tag: 'Epithet 72', desc: 'Devotional description for Deity 72' },
  { no: 73, name: 'Deity 73', tag: 'Epithet 73', desc: 'Devotional description for Deity 73' },
  { no: 74, name: 'Deity 74', tag: 'Epithet 74', desc: 'Devotional description for Deity 74' },
  { no: 75, name: 'Deity 75', tag: 'Epithet 75', desc: 'Devotional description for Deity 75' },
  { no: 76, name: 'Deity 76', tag: 'Epithet 76', desc: 'Devotional description for Deity 76' },
  { no: 77, name: 'Deity 77', tag: 'Epithet 77', desc: 'Devotional description for Deity 77' },
  { no: 78, name: 'Deity 78', tag: 'Epithet 78', desc: 'Devotional description for Deity 78' },
  { no: 79, name: 'Deity 79', tag: 'Epithet 79', desc: 'Devotional description for Deity 79' },
  { no: 80, name: 'Deity 80', tag: 'Epithet 80', desc: 'Devotional description for Deity 80' },
  { no: 81, name: 'Deity 81', tag: 'Epithet 81', desc: 'Devotional description for Deity 81' },
  { no: 82, name: 'Deity 82', tag: 'Epithet 82', desc: 'Devotional description for Deity 82' },
  { no: 83, name: 'Deity 83', tag: 'Epithet 83', desc: 'Devotional description for Deity 83' },
  { no: 84, name: 'Deity 84', tag: 'Epithet 84', desc: 'Devotional description for Deity 84' },
  { no: 85, name: 'Deity 85', tag: 'Epithet 85', desc: 'Devotional description for Deity 85' },
  { no: 86, name: 'Deity 86', tag: 'Epithet 86', desc: 'Devotional description for Deity 86' },
  { no: 87, name: 'Deity 87', tag: 'Epithet 87', desc: 'Devotional description for Deity 87' },
  { no: 88, name: 'Deity 88', tag: 'Epithet 88', desc: 'Devotional description for Deity 88' },
  { no: 89, name: 'Deity 89', tag: 'Epithet 89', desc: 'Devotional description for Deity 89' },
  { no: 90, name: 'Deity 90', tag: 'Epithet 90', desc: 'Devotional description for Deity 90' },
  { no: 91, name: 'Deity 91', tag: 'Epithet 91', desc: 'Devotional description for Deity 91' },
  { no: 92, name: 'Deity 92', tag: 'Epithet 92', desc: 'Devotional description for Deity 92' },
  { no: 93, name: 'Deity 93', tag: 'Epithet 93', desc: 'Devotional description for Deity 93' },
  { no: 94, name: 'Deity 94', tag: 'Epithet 94', desc: 'Devotional description for Deity 94' },
  { no: 95, name: 'Deity 95', tag: 'Epithet 95', desc: 'Devotional description for Deity 95' },
  { no: 96, name: 'Deity 96', tag: 'Epithet 96', desc: 'Devotional description for Deity 96' },
  { no: 97, name: 'Deity 97', tag: 'Epithet 97', desc: 'Devotional description for Deity 97' },
  { no: 98, name: 'Deity 98', tag: 'Epithet 98', desc: 'Devotional description for Deity 98' },
  { no: 99, name: 'Deity 99', tag: 'Epithet 99', desc: 'Devotional description for Deity 99' },
  { no: 100, name: 'Deity 100', tag: 'Epithet 100', desc: 'Devotional description for Deity 100' },
];
